import React, {FormEvent, useEffect, useState} from 'react';
import ReactDOM from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import './styles.css';
import {phoneCountries, normalizePhone, safeReturnUrl} from './phone';

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL,import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const clubId=()=>localStorage.getItem('clubmatch.clubId')||'';
let pendingSession: Promise<any> | null = null;
async function session(){if(pendingSession)return pendingSession;pendingSession=(async()=>{const {data,error}=await supabase.auth.getSession();if(error)throw error;if(data.session)return data.session;const r=await supabase.auth.signInAnonymously();if(r.error)throw r.error;return r.data.session;})();try{return await pendingSession;}finally{pendingSession=null;}}
async function rpc(fn:string,args:any={}){await session();const {data,error}=await supabase.rpc(fn,args);if(error)throw new Error(error.message);return data;}
const go=(p:string)=>{window.location.href=p};
const q=new URLSearchParams(location.search);
const fmt=(d:string)=>new Date(d+'T00:00:00').toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'});
function Layout({children,title='ClubMatch'}:{children:React.ReactNode,title?:string}){return <main className="page"><header className="topbar"><a className="brand" href="/">⚽ {title}</a></header>{children}</main>}
function Notice({children}:{children:React.ReactNode}){return <div className="notice" role="status">{children}</div>}
type Membership = {clubId: string; name: string; mobileNumber: string; verificationStatus: string; verificationCode: string | null};
const isVerified = (m: Membership) => ['AdminVerified', 'OtpVerified'].includes(m.verificationStatus);
const signupError = (error: any) => {
  const message = error.message || 'Please try again.';
  if (message.includes('PHONE_ALREADY_REGISTERED')) return 'This number already has a membership request. Ask the admin for help; entering it here cannot recover another account.';
  if (message.includes('INVALID_MOBILE')) return 'Enter a valid number for the selected country.';
  if (message.includes('MEMBER_VERIFICATION_REQUIRED')) return 'Your number is waiting for admin verification.';
  return message;
};
function PendingVerification({member, onRefresh}: {member: Membership; onRefresh: () => Promise<void>}) {
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState('');
  const message = `ClubMatch verification: ${member.verificationCode}. My name is ${member.name}. Please verify this request for ${member.mobileNumber}.`;
  async function refresh() { setBusy(true); setMsg(''); try { await onRefresh(); setMsg('If you still see this screen, your approval is pending.'); } catch(e) { setMsg(signupError(e)); } finally { setBusy(false); } }
  return <Layout><section className="hero-card"><p className="eyebrow">ONE-TIME VERIFICATION</p><h1>Confirm your number</h1><p className="muted">Your request is saved. An admin must verify your number before you can access the club or join matches.</p></section><section className="card action-stack"><b>{member.name} · {member.mobileNumber}</b><p>Send the code below to your club admin in WhatsApp, using the number shown above. The admin will check the sender’s number and enter your code to approve you.</p><strong className="verification-code">{member.verificationCode}</strong><button className="primary-button" onClick={() => window.open('https://wa.me/?text='+encodeURIComponent(message), '_blank', 'noopener,noreferrer')}>Open WhatsApp to send code</button><button className="secondary-button" disabled={busy} onClick={refresh}>{busy ? 'Checking…' : 'I’ve been approved — check again'}</button><a href={'/login?invite='+encodeURIComponent(localStorage.getItem('clubmatch.inviteCode')||q.get('invite')||'')+'&returnUrl='+encodeURIComponent(safeReturnUrl(q.get('returnUrl')))}>Correct my name or number</a><small className="muted">The code connects this browser’s request to your WhatsApp message. Opening WhatsApp does not verify you automatically.</small>{msg&&<Notice>{msg}</Notice>}</section></Layout>;
}
function Login() {
  const invite=q.get('invite')||localStorage.getItem('clubmatch.inviteCode')||'';
  const ret=safeReturnUrl(q.get('returnUrl')||(location.pathname.startsWith('/m/')?location.pathname+location.search:'/'));
  const [name,setName]=useState(''), [country,setCountry]=useState('+91'), [mobile,setMobile]=useState('');
  const [msg,setMsg]=useState(''), [busy,setBusy]=useState(false);
  const [pending,setPending]=useState<Membership|null>(null);
  const selected=phoneCountries.find(c=>c.code===country)!;
  async function finish(member: Membership) {
    localStorage.setItem('clubmatch.clubId',member.clubId);
    localStorage.setItem('clubmatch.inviteCode',invite);
    if(isVerified(member)) go(ret); else setPending(member);
  }
  async function submit(e:FormEvent) {
    e.preventDefault(); setBusy(true); setMsg('');
    try {
      const phone=normalizePhone(country,mobile);
      if(!phone) {setMsg('Enter a valid number for the selected country.'); return;}
      await finish(await rpc('pilot_join',{p_invite_code:invite,p_name:name.trim(),p_mobile:phone}));
    } catch(e) {setMsg(signupError(e));} finally {setBusy(false);}
  }
  if(pending) return <PendingVerification member={pending} onRefresh={async()=>{ const member=await rpc('get_my_membership'); if(member) await finish(member); }}/>;
  return <Layout><section className="hero-card"><p className="eyebrow">CLUBMATCH PILOT</p><h1>Join. Verify. Play.</h1><p className="muted">Confirm your WhatsApp number with the club admin once. This browser remembers you afterwards.</p></section><form className="card form" onSubmit={submit}><label>Your name<input required maxLength={80} autoFocus value={name} onChange={e=>setName(e.target.value)}/></label><label>WhatsApp number<select aria-label="Country code" value={country} onChange={e=>setCountry(e.target.value)}>{phoneCountries.map(c=><option key={c.code} value={c.code}>{c.label}</option>)}</select><input aria-label="WhatsApp number" required type="tel" autoComplete="tel-national" maxLength={30} value={mobile} onChange={e=>setMobile(e.target.value)} placeholder={selected.placeholder}/><small className="muted">India and GCC numbers supported. Use a number you control.</small></label><button className="primary-button" disabled={busy||!invite}>{busy?'Submitting…':'Request to Join'}</button>{!invite&&<Notice>Open the private invite link shared in WhatsApp.</Notice>}{msg&&<Notice>{msg}</Notice>}</form></Layout>;
}
function MembershipGate({children}: {children: React.ReactNode}) {
  const [member,setMember]=useState<Membership|null|undefined>();
  const [msg,setMsg]=useState('');
  async function load() {
    const m=await rpc('get_my_membership'); setMember(m);
    if(m) localStorage.setItem('clubmatch.clubId',m.clubId);
  }
  useEffect(()=>{load().catch(e=>setMsg(signupError(e)));},[]);
  if(msg) return <Layout><Notice>{msg}</Notice><button onClick={()=>{setMsg('');load().catch(e=>setMsg(signupError(e)));}}>Try again</button></Layout>;
  if(member===undefined) return <Layout><p>Checking membership…</p></Layout>;
  if(member && !isVerified(member)) return <PendingVerification member={member} onRefresh={load}/>;
  if(!member) return <Login/>;
  return <>{children}</>;
}
function Home(){return <Layout><section className="hero-card"><p className="eyebrow">OUR FOOTBALL CLUB</p><h1>Football without the collection headache.</h1><p className="muted">Share the match in WhatsApp. Players join quickly. Attendance and ₹50 payments stay accountable.</p><a className="primary-button" href="/matches/new">＋ Create Match</a></section><section className="quick-grid"><a className="quick-card" href="/payments"><b>💳 My Payments</b><span>See dues & mark paid</span></a><a className="quick-card" href="/admin/payments"><b>✅ Admin Approval</b><span>Verify payment claims</span></a><a className="quick-card" href="/admin/members"><b>👥 Members</b><span>Roles & verification</span></a><a className="quick-card" href="/settings/reminders"><b>🔔 Reminders</b><span>Preferences for pilot</span></a></section><section className="card"><h2>Club flow</h2><p className="muted">Match → actual attendance → ₹50 due → payment verification → automatic join restriction after 2 genuinely unpaid matches.</p></section></Layout>}
function CreateMatch(){const [date,setDate]=useState('');const [start,setStart]=useState('07:00');const [end,setEnd]=useState('08:00');const [turf,setTurf]=useState('');const [msg,setMsg]=useState('');async function submit(e:FormEvent){e.preventDefault();try{const r=await rpc('create_match',{p_club_id:clubId(),p_match_date:date,p_start_time:start,p_end_time:end,p_player_fee:50,p_required_players:14,p_turf_name:turf||null,p_note:null});go('/m/'+r.id)}catch(e:any){const m=e.message.match(/EXISTING_MATCH:([0-9a-f-]+)/i);if(m)go('/m/'+m[1]);else setMsg(e.message)}}return <Layout><section className="hero-card"><p className="eyebrow">NEW MATCH</p><h1>Create Friday football</h1></section><form className="card form" onSubmit={submit}><label>Date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><div className="two"><label>Start<input type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End<input type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><label>Turf / ground<input value={turf} onChange={e=>setTurf(e.target.value)} placeholder="Optional"/></label><div className="metric-grid"><div><span>Player fee</span><strong>₹50</strong></div><div><span>Ready to book</span><strong>14</strong></div></div><button className="primary-button">Create & Share</button>{msg&&<Notice>{msg}</Notice>}</form></Layout>}
function Match({id}:{id:string}){const [m,setM]=useState<any>();const [uid,setUid]=useState('');const [msg,setMsg]=useState('');async function load(){try{const s=await session();setUid(s?.user.id||'');setM(await rpc('get_match',{p_match_id:id}))}catch(e:any){if(e.message.includes('NOT_CLUB_MEMBER')){const invite=new URLSearchParams(location.search).get('invite')||localStorage.getItem('clubmatch.inviteCode')||'';if(invite)go('/login?invite='+encodeURIComponent(invite)+'&returnUrl='+encodeURIComponent('/m/'+id));else setMsg('Open this match from the private WhatsApp share link.')}else setMsg(e.message)}}useEffect(()=>{load()},[]);if(!m)return <Layout>{msg?<Notice>{msg}</Notice>:<p>Loading…</p>}</Layout>;const joined=m.players?.some((p:any)=>p.userId===uid);const share=async()=>{const invite=localStorage.getItem('clubmatch.inviteCode')||'';const sharedUrl=new URL(location.href);if(invite)sharedUrl.searchParams.set('invite',invite);const text=`⚽ Football\n📅 ${fmt(m.matchDate)}\n🕖 ${m.startTime?.slice(0,5)} – ${m.endTime?.slice(0,5)}\n💰 ₹${m.playerFee}\nAdd your name here:\n${sharedUrl.toString()}`;if(navigator.share)await navigator.share({text});else window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank')};const act=async(fn:string)=>{try{await rpc(fn,{p_match_id:id});await load()}catch(e:any){setMsg(e.message)}};return <Layout><section className="hero-card"><p className="eyebrow">{m.status}</p><h1>{fmt(m.matchDate)} · {m.startTime?.slice(0,5)}</h1><p className="muted">₹{m.playerFee} · {m.players.length}/{m.requiredPlayers} players {m.turfName?'· '+m.turfName:''}</p>{m.readyToBook&&m.status==='Open'&&<span className="status paid">Ready to book</span>}</section><section className="card"><div className="action-stack"><button className="primary-button" onClick={()=>joined?act('leave_match'):act('join_match')}>{joined?'Remove my name':'I’m Playing'}</button><button className="secondary-button" onClick={share}>Share to WhatsApp</button>{m.readyToBook&&m.status==='Open'&&<button className="secondary-button" onClick={()=>act('book_ground')}>Mark Ground Booked</button>}<a className="secondary-button" href={`/admin/matches/${id}/operations`}>Match Operations</a></div>{msg&&<Notice>{msg}</Notice>}</section><section className="card"><h2>Players</h2><div className="member-list">{m.players.map((p:any,i:number)=><div className="member-row" key={p.userId}><b>{i+1}. {p.name}</b><span>{p.userId===uid?'You':''}</span></div>)}</div></section></Layout>}
function Dues(){const [d,setD]=useState<any>();const [msg,setMsg]=useState('');const load=async()=>{try{setD(await rpc('get_my_dues',{p_club_id:clubId()}))}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);const claim=async(id:string,method:string)=>{try{await rpc('submit_payment_claim',{p_charge_id:id,p_method:method,p_note:null});load()}catch(e:any){setMsg(e.message)}};return <Layout><section className="hero-card"><h1>My Payments</h1>{d&&<><p className="muted">Total open: ₹{d.totalDue} · Unpaid matches: {d.unpaidMatches}</p>{d.blocked&&<Notice>You are blocked from joining until an unpaid match is resolved.</Notice>}</>}</section><section className="card">{msg&&<Notice>{msg}</Notice>}<div className="collection-list">{d?.charges?.map((c:any)=><div className="collection-row" key={c.chargeId}><div><b>{fmt(c.matchDate)}</b><div>₹{c.amount} · <span className={`status ${c.status==='Paid'?'paid':c.status==='ClaimPending'?'pending':'unpaid'}`}>{c.status}</span></div></div>{c.status==='Unpaid'&&<div className="pay-actions"><button onClick={()=>claim(c.chargeId,'Upi')}>I Paid UPI</button><button onClick={()=>claim(c.chargeId,'Cash')}>I Paid Cash</button></div>}</div>)}</div></section></Layout>}
function AdminPayments(){const [rows,setRows]=useState<any[]>([]);const [msg,setMsg]=useState('');const load=async()=>{try{setRows(await rpc('get_pending_payment_claims',{p_club_id:clubId()}))}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);const review=async(id:string,a:string)=>{try{await rpc('review_payment_claim',{p_claim_id:id,p_action:a,p_reason:null});load()}catch(e:any){setMsg(e.message)}};return <Layout><section className="hero-card"><h1>Payments to Verify</h1><p className="muted">Player “I Paid” claims stay pending until you approve them.</p></section><section className="card">{msg&&<Notice>{msg}</Notice>}{rows.length===0?<p>No pending claims.</p>:rows.map(c=><div className="collection-row" key={c.claimId}><div><b>{c.playerName}</b><div>₹{c.amount} · {c.method} · {fmt(c.matchDate)}</div></div><div className="pay-actions"><button onClick={()=>review(c.claimId,'approve')}>Approve</button><button onClick={()=>review(c.claimId,'reject')}>Reject</button></div></div>)}</section></Layout>}
function Attendance({id}:{id:string}){const [a,setA]=useState<any>();const [selected,setSelected]=useState<string[]>([]);const [name,setName]=useState('');const [mobile,setMobile]=useState('');const [msg,setMsg]=useState('');const load=async()=>{try{const r=await rpc('get_attendance',{p_match_id:id});setA(r);setSelected(r.registeredPlayers.filter((x:any)=>x.selected).map((x:any)=>x.userId))}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);const toggle=(u:string)=>setSelected(s=>s.includes(u)?s.filter(x=>x!==u):[...s,u]);const walk=async()=>{try{const r=await rpc('add_walk_in',{p_match_id:id,p_name:name,p_mobile:mobile});setName('');setMobile('');await load();setSelected(s=>s.includes(r.userId)?s:[...s,r.userId])}catch(e:any){setMsg(e.message)}};const final=async()=>{try{await rpc('finalize_attendance',{p_match_id:id,p_player_user_ids:selected});go('/matches/'+id+'/collection')}catch(e:any){setMsg(e.message)}};return <Layout><section className="hero-card"><h1>Finalize Actual Players</h1><p className="muted">Only selected players will owe ₹50.</p></section><section className="card">{msg&&<Notice>{msg}</Notice>}<div className="attendance-list">{a?.registeredPlayers?.map((p:any)=><label className="attendance-row" key={p.userId}><input type="checkbox" checked={selected.includes(p.userId)} onChange={()=>toggle(p.userId)}/>{p.name}</label>)}</div><div className="walkin-box"><b>Add walk-in</b><input placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="Mobile" value={mobile} onChange={e=>setMobile(e.target.value)}/><button onClick={walk}>Add</button></div><button className="primary-button top-gap" onClick={final}>Finalize Attendance ({selected.length})</button></section></Layout>}
function Collection({id}:{id:string}){const [d,setD]=useState<any>();const [msg,setMsg]=useState('');const load=async()=>{try{setD(await rpc('get_collection_dashboard',{p_match_id:id}))}catch(e:any){setMsg(e.message)}};useEffect(()=>{load()},[]);const paid=async(id:string,method:string)=>{try{await rpc('mark_charge_paid',{p_charge_id:id,p_method:method});load()}catch(e:any){setMsg(e.message)}};return <Layout><section className="hero-card"><h1>Collection Dashboard</h1>{d&&<div className="metric-grid"><div><span>Expected</span><strong>₹{d.expected}</strong></div><div><span>Paid</span><strong>₹{d.paid}</strong></div><div><span>Approval</span><strong>₹{d.pendingApproval}</strong></div><div><span>Unpaid</span><strong>₹{d.unpaid}</strong></div></div>}</section><section className="card">{msg&&<Notice>{msg}</Notice>}<div className="collection-list">{d?.players?.map((p:any)=><div className="collection-row" key={p.chargeId}><div><b>{p.playerName}</b><div>₹{p.amount} · {p.status}</div></div>{p.status!=='Paid'&&<div className="pay-actions"><button onClick={()=>paid(p.chargeId,'Cash')}>Cash</button><button onClick={()=>paid(p.chargeId,'Upi')}>UPI</button></div>}</div>)}</div><div className="action-stack top-gap"><a className="secondary-button" href={`/admin/matches/${id}/payment-report`}>Generate Pending Image</a><a className="secondary-button" href={`/admin/matches/${id}/collector`}>Assign Collector</a></div></section></Layout>}
function Members() {
  const [rows,setRows]=useState<any[]>([]), [msg,setMsg]=useState('');
  const [codes,setCodes]=useState<Record<string,string>>({});
  const [confirmed,setConfirmed]=useState<Record<string,boolean>>({});
  const [busy,setBusy]=useState('');
  const load=async()=>setRows(await rpc('get_club_members',{p_club_id:clubId()}));
  useEffect(()=>{load().catch(e=>setMsg(signupError(e)));},[]);
  async function action(m:any, kind:string) {
    setBusy(m.userId);setMsg('');
    try {
      if(kind==='approve') await rpc('approve_member_phone',{p_club_id:clubId(),p_user_id:m.userId,p_code:codes[m.userId]||''});
      if(kind==='revoke') await rpc('set_member_verified',{p_club_id:clubId(),p_user_id:m.userId,p_verified:false});
      if(kind==='role') await rpc('set_member_role',{p_club_id:clubId(),p_user_id:m.userId,p_role:m.role==='Admin'?'Player':'Admin'});
      setCodes(c=>({...c,[m.userId]:''}));setConfirmed(c=>({...c,[m.userId]:false}));await load();
    } catch(e) {setMsg(signupError(e));} finally {setBusy('');}
  }
  return <Layout><section className="hero-card"><h1>Club Members</h1><p className="muted">Approve only after receiving the player’s verification code in WhatsApp from the exact number displayed.</p></section><section className="card">{msg&&<Notice>{msg}</Notice>}<div className="member-list">{rows.map(m=><div className="member-review" key={m.userId}><div className="member-row"><div><b>{m.name}</b><div>{m.mobileNumber}</div><small>{isVerified(m)?'Verified':'Awaiting phone verification'}</small></div><button disabled={!!busy||!isVerified(m)} onClick={()=>action(m,'role')}>{m.role}</button></div>{!isVerified(m)?<div className="form"><label>Code received from this player<input aria-label={'Verification code for '+m.name} autoComplete="off" maxLength={8} value={codes[m.userId]||''} onChange={e=>setCodes(c=>({...c,[m.userId]:e.target.value.toUpperCase()}))}/></label><label className="approval-check"><input type="checkbox" checked={!!confirmed[m.userId]} onChange={e=>setConfirmed(c=>({...c,[m.userId]:e.target.checked}))}/>I checked that the WhatsApp sender’s number is {m.mobileNumber}.</label><button className="primary-button" disabled={!!busy||!confirmed[m.userId]||!/^[A-F0-9]{8}$/.test(codes[m.userId]||'')} onClick={()=>action(m,'approve')}>{busy===m.userId?'Approving…':'Approve Number'}</button></div>:<button disabled={!!busy||m.role==='Admin'} onClick={()=>action(m,'revoke')}>Remove verification</button>}</div>)}</div></section></Layout>;
}
function Collector({id}:{id:string}){const [rows,setRows]=useState<any[]>([]);const [msg,setMsg]=useState('');useEffect(()=>{rpc('get_collector_options',{p_match_id:id}).then(setRows).catch((e:any)=>setMsg(e.message))},[]);const set=async(u:string)=>{try{await rpc('assign_collector',{p_match_id:id,p_user_id:u});go('/matches/'+id+'/collection')}catch(e:any){setMsg(e.message)}};return <Layout><section className="hero-card"><h1>Assign Collector</h1><p className="muted">Collector can record cash/UPI for this match only.</p></section><section className="card">{msg&&<Notice>{msg}</Notice>}{rows.map(m=><div className="member-row" key={m.userId}><b>{m.name}</b><button onClick={()=>set(m.userId)}>{m.assigned?'Assigned':'Assign'}</button></div>)}</section></Layout>}
function Operations({id}:{id:string}){const [msg,setMsg]=useState('');const act=async(fn:string)=>{try{await rpc(fn,{p_match_id:id,p_reason:null});if(fn==='complete_match')go('/admin/matches/'+id+'/attendance');else go('/m/'+id)}catch(e:any){setMsg(e.message)}};return <Layout><section className="hero-card"><h1>Match Operations</h1></section><section className="card action-stack">{msg&&<Notice>{msg}</Notice>}<button className="primary-button" onClick={()=>act('complete_match')}>Match Completed → Finalize Attendance</button><a className="secondary-button" href={`/admin/matches/${id}/attendance`}>Attendance</a><a className="secondary-button" href={`/matches/${id}/collection`}>Collection</a><button className="danger-button" onClick={()=>act('cancel_match')}>Cancel Match</button></section></Layout>}
function Report({id}:{id:string}){const [r,setR]=useState<any>();const canvas=React.useRef<HTMLCanvasElement>(null);const [msg,setMsg]=useState('');useEffect(()=>{rpc('get_pending_payment_report',{p_match_id:id}).then(setR).catch((e:any)=>setMsg(e.message))},[]);useEffect(()=>{if(!r||!canvas.current)return;const c=canvas.current,ctx=c.getContext('2d')!;const h=400+Math.max(1,r.pendingPlayers.length)*62;c.width=1080;c.height=h;ctx.fillStyle='#f7fbf8';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#0b7a3d';ctx.fillRect(0,0,1080,180);ctx.fillStyle='white';ctx.font='700 58px Arial';ctx.fillText('⚽ ClubMatch',60,78);ctx.font='32px Arial';ctx.fillText(`${fmt(r.matchDate)} · Payment Pending`,60,132);ctx.fillStyle='#173b29';ctx.font='700 32px Arial';ctx.fillText(`Played ${r.playedCount}   Paid ${r.paidCount}   Approval ${r.pendingApprovalCount}   Unpaid ${r.unpaidCount}`,60,245);ctx.font='28px Arial';ctx.fillStyle='#5c6f63';ctx.fillText(`Total pending: ₹${r.totalPending}`,60,300);let y=370;ctx.fillStyle='#173b29';r.pendingPlayers.forEach((p:any)=>{ctx.font='700 30px Arial';ctx.fillText(`${p.number}. ${p.playerName}`,70,y);ctx.textAlign='right';ctx.fillText(`₹${p.amount}`,1000,y);ctx.textAlign='left';y+=62})},[r]);const share=async()=>{if(!canvas.current)return;canvas.current.toBlob(async blob=>{if(!blob)return;const file=new File([blob],`clubmatch-pending-${r.matchDate}.png`,{type:'image/png'});try{if(navigator.share&&navigator.canShare?.({files:[file]}))await navigator.share({files:[file],text:'Pending football payments'});else{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();window.open('https://wa.me/?text='+encodeURIComponent('Pending football payments'),'_blank')}}catch{}},'image/png')};return <Layout><section className="hero-card"><h1>Pending Payment Image</h1><p className="muted">Pending-approval players are excluded from the unpaid list.</p></section><section className="card">{msg&&<Notice>{msg}</Notice>}<div className="report-preview"><canvas ref={canvas}/></div><button className="primary-button top-gap" onClick={share}>Share Image to WhatsApp</button></section></Layout>}
function Reminders(){const [m,setM]=useState(true),[p,setP]=useState(true),[msg,setMsg]=useState('');useEffect(()=>{rpc('get_reminder_preferences',{p_club_id:clubId()}).then(r=>{setM(r.matchReminderEnabled);setP(r.paymentReminderEnabled)}).catch(()=>{})},[]);const save=async()=>{try{await rpc('set_reminder_preferences',{p_club_id:clubId(),p_match_enabled:m,p_payment_enabled:p});setMsg('Saved.') }catch(e:any){setMsg(e.message)}};return <Layout><section className="hero-card"><h1>Reminder Preferences</h1></section><section className="card"><label className="toggle-row"><span><b>Match reminders</b><small>Preference saved for future notification work.</small></span><input type="checkbox" checked={m} onChange={e=>setM(e.target.checked)}/></label><label className="toggle-row"><span><b>Payment reminders</b><small>Preference saved for future notification work.</small></span><input type="checkbox" checked={p} onChange={e=>setP(e.target.checked)}/></label><button className="primary-button top-gap" onClick={save}>Save</button>{msg&&<Notice>{msg}</Notice>}</section></Layout>}
function Routes(){const p=location.pathname;const match=(re:RegExp)=>p.match(re);let m;if(p==='/login')return <Login/>;if(p==='/')return <Home/>;if(p==='/matches/new')return clubId()?<CreateMatch/>:<Login/>;if(p==='/payments')return <Dues/>;if(p==='/admin/payments')return <AdminPayments/>;if(p==='/admin/members')return <Members/>;if(p==='/settings/reminders')return <Reminders/>;if((m=match(/^\/m\/([0-9a-f-]+)$/i)))return <Match id={m[1]}/>;if((m=match(/^\/admin\/matches\/([0-9a-f-]+)\/attendance$/i)))return <Attendance id={m[1]}/>;if((m=match(/^\/matches\/([0-9a-f-]+)\/collection$/i)))return <Collection id={m[1]}/>;if((m=match(/^\/admin\/matches\/([0-9a-f-]+)\/collector$/i)))return <Collector id={m[1]}/>;if((m=match(/^\/admin\/matches\/([0-9a-f-]+)\/operations$/i)))return <Operations id={m[1]}/>;if((m=match(/^\/admin\/matches\/([0-9a-f-]+)\/payment-report$/i)))return <Report id={m[1]}/>;return <Layout><h1>Page not found</h1><a href="/">Back home</a></Layout>}
function App(){return location.pathname==='/login'?<Login/>:<MembershipGate><Routes/></MembershipGate>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);